[general]
pipeline_url = "http://ci.papercode.net:8080/teams/main/pipelines/aoc2022"
year = 2022

[participants.mattcl]
username = "mattcl"
repo = "https://github.com/mattcl/aoc2022"
location = "/home/matt/code/aoc2022"
language = "rust"
input_cmd = "ci/input_path.sh"
entrypoint = "aoc run"
is_solver = true
