[general]
pipeline_url = "http://ci.papercode.net:8080/teams/main/pipelines/aoc2022"
year = 2022

[participants.mattcl]
username = "mattcl"
repo = "https://github.com/mattcl/aoc2022"
location = "/home/matt/code/aoc2022"
input_cmd = "ci/input_path.sh"
entrypoint = "/home/matt/code/aoc2022/target/release/aoc run"
is_solver = true

[participants.mattcl-dev]
username = "mattcl"
repo = "https://github.com/mattcl/aoc2023"
location = "/home/matt/code/aoc2022"
input_cmd = "ci/input_path.sh"
entrypoint = "/home/matt/code/aoc2022/target/debug/aoc run"
skip_inputs = true
